# Site settings
title: Coding in the Desert
header-img: img/home-bg.png
email: jenn.leigh.hansen@gmail.com
copyright_name: hansenjl
description: > # this means to ignore newlines until "baseurl:"
  The journey to change careers and cities
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hansenjl
learn_profile: hansenjl
email_username: jenn.leigh.hansen@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
